### ISSUE TITLE
Can't find the AES key

### ISSUE THREAD

**Issue by imronin97** [Cracko298/UE4-AES-Key-Extracting-Guide#10]
After running the Find_AES_Key.bat, it generated 22 folders and every one of them has a file with a number. Which one is the AES Key?
![2024_11_ 7_03_49_11](https://github.com/user-attachments/assets/0a2253e5-6459-4cfc-8965-311642fc49e1)

**Comment by Cracko298** [comment]
The guide states one of the files inside of the folders has the key as the filename, minus the extension if present.

These are keys that are found throughout the shipping.exe as such, one could be the aes key to save encryption, another could be to encrypt online communication, or encrypt player data. You simply can't know for sure.

Your best bet is to try the one that looks the most random, and if that doesn't work all I can suggest is going through them 1 by 1.

**Comment by Cracko298** [comment]
Author hasn't responded, assuming issue was resolved.
