### ISSUE TITLE
Hey i wanted to ask if anybody could help me solve this issue

### ISSUE THREAD

**Issue by SK1D1092** [Cracko298/UE4-AES-Key-Extracting-Guide#2]
iam currently getting rid of DRM restriction on the game the UE version is 4.27.1 but the steamless wrote that "the system cannot find the path specified."

**Comment by Cracko298** [comment]
Here's an example: "Steam\steamapps\common\Ice Station Z\ISZ\Binaries\Win64\YourUE4Game-Shipping.exe"
you need to include the.exe in the path, not just the directory.

If this still doesn't resolve your issue/problem, you can send a screenshot here what steamless is pointing too.

**Comment by SK1D1092** [comment]
my bad i already solved it (it did not have any DRM restrictions weird) but thanks btw is there any way to find out which AES key is the right key cause it showed me like 9 or 10 other keys and idk which key is the right one.

**Comment by Cracko298** [comment]
Sure thing, you can get rid of most of the keys, some known fake keys are as follows:
0x0000803F0000803F0000803F0000803F000048430000F0410AD7A33C0000803F
0x9A99993E0000803F0000003F0000003F04000000060000000000003F00030303

if they have multiple characters, or repeating characters in this example it's a whole lot of 0's with some 3F's evenly spaced between 'em.

This should narrow it down to two or three keys, in which case it's all trial and error.

**Comment by SK1D1092** [comment]
thanks man helped a lot

**Comment by Cracko298** [comment]
If you're using Umodel (UEViewer), you can just use multiple aes-keys, fmodel is more of trial and error (but I prefer fmodel anyway).

If this issue is resolved on your end, I'll close the GitHub issue.

**Comment by SK1D1092** [comment]
ye i think it is you helped a lot thanks
