### ISSUE TITLE
hey i have this issue with UEViewer

### ISSUE THREAD

**Issue by SK1D1092** [Cracko298/UE4-AES-Key-Extracting-Guide#3]
![Screenshot_65](https://github.com/Cracko298/UE4-AES-Key-Extracting-Guide/assets/135438710/19004685-396e-4206-8045-4392d50d0996)

![Screenshot_63](https://github.com/Cracko298/UE4-AES-Key-Extracting-Guide/assets/135438710/b0577ff7-98d3-424a-9adc-83ee372cf08f)

![Screenshot_66](https://github.com/Cracko298/UE4-AES-Key-Extracting-Guide/assets/135438710/b41ecc8f-cb25-4f2f-ba76-6a4c30034744)

i dont understand what did i do wrong the game version is 4.27.1 if it would help

**Comment by Cracko298** [comment]
You can try [FModel](https://fmodel.app/) and see if it gives you the same result.
As [Umodel](https://www.gildor.org/en/projects/umodel) has proven to be extremely buggy, especially when handling obfuscation techniques.

**Comment by Cracko298** [comment]
The minor version also does not matter. You only need "4.27", not "4.27.1" in your case.

The layout is as follows:
- Number 4   = Unreal Version
- Number 27 = Major Release
- Number 1   = Minor Release

**Comment by SK1D1092** [comment]
ok but i tried f model and UEviewer and still none of them could load the pak file so i dont understand why

**Comment by SK1D1092** [comment]
and the aes key prompt wont come up

**Comment by Cracko298** [comment]
By chance does the game you're trying to mod have more than one *.pak file?

**Comment by SK1D1092** [comment]
no it have only 1 pak file

**Comment by SK1D1092** [comment]
ok rn the f model wrote me this error System.ArgumentException: Given directory must exist (Parameter '_workingDirectory')
   at CUE4Parse.FileProvider.DefaultFileProvider.Initialize()

**Comment by Cracko298** [comment]
Do you have any of the following characters in any of the paths that lead to the Umodel or Fmodel directory?

\ / ? " < > |

**Comment by SK1D1092** [comment]
C:\Users\---\Downloads\pak file

**Comment by Cracko298** [comment]
The error means that there are invalid characters that C++/C# cannot parse correctly. Thus giving the error provided. This also includes but not limited to the special characters such as japanese, chinese, or arabic.

Make sure that there are also no invisible characters that aren't spaces.

**Comment by Cracko298** [comment]
You could attempt to fix it by using a USB drive, or external drive/SDHC card.
If that doesn't work, you will need to make an issue on FModel, or UModel GitHub repos, make sure to include the error that you had sent earlier in the one to FModel's GitHub Repo.

**Comment by SK1D1092** [comment]
nah i fixed it beacause it was in the steam folder and it usually dont work there when i try it but when i grab it from the steam file and place it in desktop or downloads it wont say any error so i think there is no help here :D

**Comment by SK1D1092** [comment]
still wont load tho

**Comment by Cracko298** [comment]
If you already tried this: https://github.com/Cracko298/UE4-AES-Key-Extracting-Guide/issues/3#issuecomment-1575017228

I would recommend creating an issue with FModel, or UModel, make sure to include screenshots of errors, directories, and details about your game in the report. This could take several days.

**Comment by SK1D1092** [comment]
ok so fmodel support wont answer me for no reason and they even deleted my post :D but i found this on their discord do you know what does that mean?
![Screenshot_69](https://github.com/Cracko298/UE4-AES-Key-Extracting-Guide/assets/135438710/c59dc14f-2192-45c6-9b49-a785b5f1bdbb)

**Comment by Cracko298** [comment]
Both applications do not open it. You can't open the game through FModel.
I'll leave this issue open, just in case somebody else comes across this issue and has found a solution to it.

**Comment by SK1D1092** [comment]
so I found what I need but I wanted to ask fmodel uses dev uncompiled version that I need, do you happen to know how to compile it so I can run it bcs it has the version of the game i need.

**Comment by Cracko298** [comment]
https://stackoverflow.com/questions/7987264/how-do-you-compile-c

**Comment by Cracko298** [comment]
> ok i got everything i needed and i thank you wanted to ask just one thing if you maybe happend to know how to execute files that are in the game files but are not in the game

You can't execute not executable files, unless you have a compiler, or Interpreter. I'm not sure if you're English, sorry if I was a bit technical.

You can't execute files within a .pak file.
You can modify .uasset (with UAsset GUI or API) files, and install em using UMU *Unreal Mod Unlocker by Illusionary Software (GHFear).

**Comment by SK1D1092** [comment]
yeah i meant that thanks :D
