### ISSUE TITLE
0 AES File found

### ISSUE THREAD

**Issue by IntenseParijat** [Cracko298/UE4-AES-Key-Extracting-Guide#7]
I wanted to extract the audio files from the new release game "Wuthering Waves" on Epic Games (Non-Steam).
As expected, it failed (Now imma suck on my thumb)...

> C:\Users\parij\Downloads\AESKeyFinder-By-GHFear-main>echo off
> 
> QuickBMS generic files extractor and reimporter 0.9.2 (64bit test)
> by Luigi Auriemma
> e-mail: me@aluigi.org
> web:    aluigi.org
>         (Nov 25 2018 - 11:44:48)
> 
>                    quickbms.aluigi.org  Homepage
>                             zenhax.com  ZenHAX Forum
>                      @zenhax @quickbms  Twitter & Scripts
> 
> 
> No SteamStub DMR detected. Hit Enter/Return to continue scanning!
> 
> Press any key to continue . . .
> 
> QuickBMS generic files extractor and reimporter 0.9.2 (64bit test)
> by Luigi Auriemma
> e-mail: me@aluigi.org
> web:    aluigi.org
>         (Nov 25 2018 - 11:44:48)
> 
>                    quickbms.aluigi.org  Homepage
>                             zenhax.com  ZenHAX Forum
>                      @zenhax @quickbms  Twitter & Scripts
> 
> 
> Unreal Engine Version: 4.26 [ is supported ]
> 
> By downloading and using this tool you agree that this tool is for research purposes only and that I (GHFear) am not responsible for what (you) the end user does with it.
> 
> Press any key to continue . . .
> 
> QuickBMS generic files extractor and reimporter 0.9.2 (64bit test)
> by Luigi Auriemma
> e-mail: me@aluigi.org
> web:    aluigi.org
>         (Nov 25 2018 - 11:44:48)
> 
>                    quickbms.aluigi.org  Homepage
>                             zenhax.com  ZenHAX Forum
>                      @zenhax @quickbms  Twitter & Scripts
> 
> - open input file C:\Users\parij\Downloads\AESKeyFinder-By-GHFear-main\Client-Win64-Shipping.exe
> - open script scripts\findaes.bms
> - set output folder .
> 
>   offset           filesize   filename
> --------------------------------------
> ..........::::::::::256-BIT AES KEY RECOVERY - BY GHFEAR::::::::::.......... SCAN: 1/3 : Version 2.0
> 
> 
> 
> 
> Finding 256-bit AES Keys in Client-Win64-Shipping.exe (This should be pretty quick!).
> 
> 
> - 0 files found in 3 seconds
>   coverage file 0   1821%   1266024303 69521304   . offset 000000000424cee4
> 
> QuickBMS generic files extractor and reimporter 0.9.2 (64bit test)
> by Luigi Auriemma
> e-mail: me@aluigi.org
> web:    aluigi.org
>         (Nov 25 2018 - 11:44:48)
> 
>                    quickbms.aluigi.org  Homepage
>                             zenhax.com  ZenHAX Forum
>                      @zenhax @quickbms  Twitter & Scripts
> 
> - open input file C:\Users\parij\Downloads\AESKeyFinder-By-GHFear-main\Client-Win64-Shipping.exe
> - open script scripts\findaes2.bms
> - set output folder .
> 
>   offset           filesize   filename
> --------------------------------------
> ..........::::::::::256-BIT AES KEY RECOVERY - BY GHFEAR::::::::::.......... SCAN: 2/3 : Version 2.0
> 
> 
> 
> 
> Finding 256-bit AES Keys in Client-Win64-Shipping.exe (This should be pretty quick!).
> 
> 
> - 0 files found in 3 seconds
>   coverage file 0   1825%   1268899442 69521304   . offset 000000000424cee3
> 
> QuickBMS generic files extractor and reimporter 0.9.2 (64bit test)
> by Luigi Auriemma
> e-mail: me@aluigi.org
> web:    aluigi.org
>         (Nov 25 2018 - 11:44:48)
> 
>                    quickbms.aluigi.org  Homepage
>                             zenhax.com  ZenHAX Forum
>                      @zenhax @quickbms  Twitter & Scripts
> 
> - open input file C:\Users\parij\Downloads\AESKeyFinder-By-GHFear-main\Client-Win64-Shipping.exe
> - open script scripts\findaes3.bms
> - set output folder .
> 
>   offset           filesize   filename
> --------------------------------------
> ..........::::::::::256-BIT AES KEY RECOVERY - BY GHFEAR::::::::::.......... SCAN: 3/3 : Version 2.0
> 
> 
> 
> 
> Finding 256-bit AES Keys in Client-Win64-Shipping.exe (This should be pretty quick!).
> 
> 
> - 0 files found in 3 seconds
>   coverage file 0   1820%   1265952687 69521304   . offset 000000000424cee4
> Press any key to continue . . .

Any tips to stop me from sucking on my thumb is welcome...

**Comment by Cracko298** [comment]
It's probably due to an Epic Games DRM or some sort of Prevention method in place by the game Developers, if this was Steam I would be able to help, but unfortunately I know next to nothing about how games distributed on Epic Games Store work.

**Comment by IntenseParijat** [comment]
Guess what? I need to learn to open exes' now...
Btw, it has its own launcher which is downloaded from epic, from which the game is to be downloaded.

**Comment by Cracko298** [comment]
Than this guide probably wouldn't work for you, a Launcher and a Game are quite different.

**Comment by IntenseParijat** [comment]
No, I was talking about that game.
First we need to download the launcher from Epic store, then download the game from the Launcher, after that we have to launch the game from the launcher which will open the game in another shipping.exe
2 step process instead of direct launch from epic
