### ISSUE TITLE
AES keys don't work

### ISSUE THREAD

**Issue by VitriolExhaust** [Cracko298/UE4-AES-Key-Extracting-Guide#9]
Hi Cracko298, 

I am using your method to extract the AES keys for Dark and Darker. The devs are comfortable with players datamining, so there isn't any DRM steam restriction. I am using the file called DungeonCrawler.exe that is found at "Dark and Darker/Binaries/Win64/DungeonCrawler.exe"

When I run this through the AES key finder, it creates 18 different folders and none of these keys are the key that decrypts the game files. (I have noticed some of the keys are double ups, or in the case of one key, it shows up 5 times.)

I know Dark and Darker was created on Unreal Engine 4 then moved to Unreal Engine 5 later in development, so I thought perhaps this might be a cause of confusion for key finder. 

I'm not really sure what I should do from here, so if you could point me in the right direction, I would greatly appreciate it.

Thank you for your time,
Kind Regards,
Vitriol Exhaust

![keys](https://github.com/user-attachments/assets/4eba08de-81e0-4c56-b57f-a15204be2bc4)
![folder with file in it](https://github.com/user-attachments/assets/de5fa91d-6e0e-47f9-9e92-edc19a1f1ddf)
![Folder with Dark and Darker Files](https://github.com/user-attachments/assets/9b18d5a4-9a1b-4aed-a78a-747343cfb61d)

**Comment by Cracko298** [comment]
Thank you for submitting an issue.

Using this guide for Games with UE5 requires v5.0 or v5.1 (mileage may vary with this release).

If the game you're working with uses a newer version of UE5 or v5.1 and still has said issue. There is nothing I can do myself. You would have to find another way to get said keys for the `.pak` files. There are a few methods for newer UE5 games if you would like I can link them below.

**Comment by Cracko298** [comment]
If the game uses a v5.0 release and doesn't work, there may be it might just be a one-off thing, and if so, you should probably use a different key finder for your game

**Comment by VitriolExhaust** [comment]
I was able to find a working key in a discord in the end :) Not sure how they got their key but hey, it works! :D

Thanks for your thoughts cracko! All the best to you!
